FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
#FROM tensorflow/tensorflow:1.3.0-devel-gpu-py3

# Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID=${UID}
ARG SHELL=/bin/bash

# Replace apt urls
#RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list

# Install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    wget curl ssh \
    zsh terminator gnome-terminal git vim tig \
    dbus-x11 libgl1 libxext6 libx11-6 \
#    libglvnd0 libglx0 libegl1 \ # Occures error in ubuntu 16.04
#    python-catkin-tools \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y python3.4 python3.4-dev python3-pip \
                          libboost-all-dev libboost-python-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install python packages
RUN pip3 install --upgrade pip && pip3 install matplotlib imageio tk \
    Cython==0.28.4 gym==0.9.4 tensorflow-gpu==1.3.0 numpy==1.13.3 \
    jupyter scipy

# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# Setup users and groups
RUN groupadd --gid ${GID} ${GROUP} \
  && useradd --gid ${GID} --uid ${UID} -ms ${SHELL} ${USER} \
  && mkdir -p /etc/sudoers.d \
  && echo "${USER}:x:${UID}:${UID}:${USER},,,:$HOME:${shell}" >> /etc/passwd \
  && echo "${USER}:x:${UID}:" >> /etc/group \
  && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}" \
  && chmod 0440 "/etc/sudoers.d/${USER}"

# copy entrypoint
COPY entrypoint.bash /entrypoint.bash
RUN chmod 777 /entrypoint.bash

# setup terminator config
RUN mkdir -p /home/${USER}/.config/terminator
COPY config/terminator/config /home/${USER}/.config/terminator
#RUN sudo chown -R ${USER}:${GROUP} /home/${USER}/.config
RUN chown -R ${USER}:${GROUP} /home/${USER}/.config

# Switch user to ${USER}
#USER ${USER}

# Make SSH available
EXPOSE 22

# Switch to user's HOME folder
WORKDIR /home/${USER}

# CMD ["terminator"]
#ENTRYPOINT ["/entrypoint.bash", "terminator"]
ENTRYPOINT ["terminator"]

